language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.5
  
before_script:
  - echo "no tests"
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - kubectl version --short --client
  
Install:
  - docker-compose -f docker-compose.yml build --parallel 
  - docker-compose -f docker-compose.yml push

