# This file is used for convenience of local development.
# DO NOT STORE YOUR CREDENTIALS INTO GIT
POSTGRES_USERNAME=
POSTGRES_PASSWORD= 
POSTGRES_HOST=
POSTGRES_DATABASE=
AWS_MEDIA_BUCKET=
AWS_REGION=
AWS_PROFILE=
JWT_SECRET=
